### ISSUE TITLE
[$env open] -fidexmap default

### ISSUE THREAD

**Issue by gahr** [ray2501/tcl-lmdb#4]
Hi Danilo,

I see that the `-fixedmap` param to `env open` defaults to true.
https://github.com/ray2501/tcl-lmdb/blob/master/generic/tclmdb.c#L1363
This is very risky as `mmap(2)` doesn't guarantee that the address hint is respected.
As you only open the env once - when doing `$env open` - and copy data in/out via `Tcl_Obj`s, I wonder why you chose to opt for having this default to true.

If there's no compelling reason, I think it would be better to change the default to false.

Thanks!

**Comment by ray2501** [comment]
I just follow the LMDB test code and not think about this.
I will fix this.

**Comment by gahr** [comment]
I have to double check, but I _think_ this might be the cause for the testsuite failures I see when building in debug mode (--enable-symbols passed to configure). Can you reproduce?

**Comment by ray2501** [comment]
I can't reproduce. It is still pass on my machine (at openSUSE).

**Comment by gahr** [comment]
I'll have a closer look at it and let you know!

**Comment by gahr** [comment]
Turns out this wasn't the reason for the failure I was seeing. Investigating that in #5 .
